apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundedcontext5152941176470588
  labels:
    app: boundedcontext5152941176470588
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boundedcontext5152941176470588
  template:
    metadata:
      labels:
        app: boundedcontext5152941176470588
    spec:
      containers:
        - name: boundedcontext5152941176470588
          image: "username/boundedcontext5152941176470588:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
