name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./boundedcontext156/pom.xml
          mvn clean package -f ./boundedcontext706/pom.xml
          mvn clean package -f ./boundedcontext1185/pom.xml
          mvn clean package -f ./boundedcontext5152941176470588/pom.xml

      - name: Docker Build and push for Boundedcontext156
        uses: docker/build-push-action@v4
        with:
          context: ./boundedcontext156
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/boundedcontext156:latest
            ghcr.io/${{ github.repository }}/boundedcontext156:${{ github.ref_name }}
            
      - name: Docker Build and push for Boundedcontext706
        uses: docker/build-push-action@v4
        with:
          context: ./boundedcontext706
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/boundedcontext706:latest
            ghcr.io/${{ github.repository }}/boundedcontext706:${{ github.ref_name }}
            
      - name: Docker Build and push for Boundedcontext1185
        uses: docker/build-push-action@v4
        with:
          context: ./boundedcontext1185
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/boundedcontext1185:latest
            ghcr.io/${{ github.repository }}/boundedcontext1185:${{ github.ref_name }}
            
      - name: Docker Build and push for Boundedcontext5152941176470588
        uses: docker/build-push-action@v4
        with:
          context: ./boundedcontext5152941176470588
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/boundedcontext5152941176470588:latest
            ghcr.io/${{ github.repository }}/boundedcontext5152941176470588:${{ github.ref_name }}
            
